<?php
function sending_email_by_phpmailer($smtp,$username,$password,$emailto,$to,$port,$host,$gift_card,$email_content){

	// Thiết lập SMTP Server
	require_once(STRIPE_BASE_DIR . '/phpmailer/class.phpmailer.php');// nạp thư viện

	//Khởi tạo đối tượng
	$mail = new PHPMailer();

	/*=====================================
	* THIET LAP THONG TIN GUI MAIL
	*=====================================*/

	$mail->IsSMTP(); // Gọi đến class xử lý SMTP
	$mail->Host       = $host;     // tên SMTP server
	//$mail->SMTPDebug  = 2;                    // enables SMTP debug information (for testing)
                                           // 1 = errors and messages
                                           // 2 = messages only
	$mail->SMTPAuth   = true;                  // Sử dụng đăng nhập vào account
	$mail->SMTPSecure = $smtp;
	$mail->Host       = $host;         // Thiết lập thông tin của SMPT
	$mail->Port       = $port;                            // Thiết lập cổng gửi email của máy
	$mail->Username   = $username."@gmail.com";     // SMTP account username
	$mail->Password   = $password;                // SMTP account password

	/*=====================================
	* DUA THONG TIN TU FORM GUI EMAIL VAO
	*=====================================*/
	//Thiet lap thong tin nguoi gui va email nguoi gui
	$mail->SetFrom($mail->Username ,"ThaiArtofMassage");

	//Thiết lập thông tin người nhận
	$mail->AddAddress($emailto,$to) ;
	$mail->AddAddress($mail->Username ,"ThaiArtofMassage"); //thêm mail người nhận
	//Thiết lập email nhận email hồi đáp
	//nếu người nhận nhấn nút Reply
	$mail->AddReplyTo($mail->Username ,"ThaiArtofMassage");

	/*=====================================
	* THIET LAP NOI DUNG EMAIL
	*=====================================*/

	 //Thiết lập tiêu đề
	 $mail->Subject    = 'Thank you for purchasing gift certificate';

	 //Thiết lập định dạng font chữ
	 $mail->CharSet = "utf-8";

	 $mail->AltBody = "To view the message, please use an HTML compatible email viewer!";

	 //Thiết lập nội dung chính của email
	 $body  = '';
	 $body  = eregi_replace("[\\]",'',$body);

	 
	 
	 $body .= $email_content;
	 

	// Đính kèm thêm file, không đính thì bỏ qua
	 $mail->AddAttachment($gift_card, 'gift_card.jpg'); // attach ảnh vào, file này nằm trên host
	
	 $mail->MsgHTML($body);
	
	 
	if(!$mail->Send()) {
		
		return $mail->ErrorInfo;
	} else {
		
		return 1;
	}
	
}

function pippin_stripe_process_payment() {
	if(isset($_POST['action']) && $_POST['action'] == 'stripe' && wp_verify_nonce($_POST['stripe_nonce'], 'stripe-nonce')) {
 
		global $stripe_options;
 
		// load the stripe libraries
		require_once(STRIPE_BASE_DIR . '/lib/Stripe.php');
                
		// retrieve the token generated by stripe.js
		$token = $_POST['stripeToken'];
 
		// check if we are using test mode
		if(isset($stripe_options['test_mode']) && $stripe_options['test_mode']) {
			$secret_key = $stripe_options['test_secret_key'];
		} else {
			$secret_key = $stripe_options['live_secret_key'];
		}
 
		// attempt to charge the customer's card
		try {
			/*process*/
			//client
			$gift_email       = $_POST['card-email'];
			$gift_number      = $_POST['gift_number'];
			$money            = $_POST['card-amount'];
			$to               = $_POST['card-to'];
			$from             = $_POST['card-from'];
			$note             = $_POST['card-note'];
			//config
			$img              = $stripe_options['gift'.$gift_number.'_image'];
			$username	  = $stripe_options['email_username'];
			$password	  = $stripe_options['email_password'];	
			$port		  = (isset($stripe_options['email_port']))?$stripe_options['email_port']:"465" ;
			$host		  = (isset($stripe_options['email_host']))?$stripe_options['email_host']:"smtp.gmail.com" ;
			$smtp		  = (isset($stripe_options['email_smtpsecure']))?$stripe_options['email_smtpsecure']:"ssl" ;
			$send_by          = (isset($stripe_options['php_mailer']))?$stripe_options['php_mailer']: 0 ;
			$send_content     = (isset($stripe_options['edit_email_content']))?$stripe_options['edit_email_content']: '' ;
			$account_mail     = (isset($stripe_options['email_account']))?$stripe_options['email_account']: '' ;
			$gift_code        = (isset($stripe_options['gift_code']))?$stripe_options['gift_code']: 0 ;
			//Thanh toan
			Stripe::setApiKey($secret_key);
			$charge = Stripe_Charge::create(array(
					'amount' => $money*100, // $10
					'currency' => 'usd',
					'card' => $token/*,
                                        'application_fee' => 500*/
				)				
			);

			//sinh the qua
			require_once(STRIPE_BASE_DIR . '/card/create_gift_card.php');
			$gift_card = create_gift_card($img,$to,$from,$money,$note,$gift_code);
			if (!file_exists($gift_card)) {
				
				throw new Exception('can not generate gift card');
			}
			//Su ly noi dung thu 
			//<body text='black'>
			$send_content = str_replace("%from%", $from, $send_content);
			$send_content = str_replace("%to%", $to, $send_content);
			$send_content = str_replace("%note%", $note, $send_content);
			$send_content = str_replace("%money%", $money, $send_content);
			//Gui email
			if($send_by == 1){
				$be = sending_email_by_phpmailer($smtp,$username,$password,$gift_email,$from,$port,$host,$gift_card,$send_content);
				if($be != 1){
					unlink($gift_card);
					throw new Exception($be);
				}
			}
			else{
				require_once(STRIPE_BASE_DIR . '/phpmailer/My_Php_Mail.php');
				$c = new My_Php_Mail();
				$be = $c->add_receivers(array($gift_email,$account_mail))->add_sender_mail($account_mail)->add_sender_name("Thaiartofmassage")->add_subject('Thank you for purchasing gift certificate')->add_message($send_content)->add_file($gift_card)->send();
				if($be != 1){
					unlink($gift_card);
					throw new Exception('can"t not sending email');
				}
			}

			//xoa the qua
			unlink($gift_card);


			// redirect on successful payment
			$redirect = add_query_arg('payment', 'paid', $_POST['redirect']);
			
		} catch (Exception $e) {
			// redirect on failed payment
			$redirect = add_query_arg('payment', 'failed', $_POST['redirect']);
                        //echo  $e->getMessage();
		}
 
		// redirect back to our previous page with the added query variable
		wp_redirect($redirect); exit;
	}
}
add_action('init', 'pippin_stripe_process_payment');
